location: .gitman
sources:
- name: mrs_bumper
  type: git
  repo: https://github.com/ctu-mrs/mrs_bumper.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_bumper
  scripts:
  - git submodule update --init --recursive
- name: mrs_lib
  type: git
  repo: https://github.com/ctu-mrs/mrs_lib.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_lib
  scripts:
  - git submodule update --init --recursive
- name: mrs_mavros_interface
  type: git
  repo: https://github.com/ctu-mrs/mrs_mavros_interface.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_mavros_interface
  scripts:
  - git submodule update --init --recursive
- name: mrs_msgs
  type: git
  repo: https://github.com/ctu-mrs/mrs_msgs.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_msgs
  scripts:
  - git submodule update --init --recursive
- name: mrs_optic_flow
  type: git
  repo: https://github.com/ctu-mrs/mrs_optic_flow.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_optic_flow
  scripts:
  - git submodule update --init --recursive
- name: mrs_uav_controllers
  type: git
  repo: https://github.com/ctu-mrs/mrs_uav_controllers.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_uav_controllers
  scripts:
  - git submodule update --init --recursive
- name: mrs_uav_general
  type: git
  repo: https://github.com/ctu-mrs/mrs_uav_general.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_uav_general
  scripts:
  - git submodule update --init --recursive
- name: mrs_uav_managers
  type: git
  repo: https://github.com/ctu-mrs/mrs_uav_managers.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_uav_managers
  scripts:
  - git submodule update --init --recursive
- name: mrs_uav_odometry
  type: git
  repo: https://github.com/ctu-mrs/mrs_uav_odometry.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_uav_odometry
  scripts:
  - git submodule update --init --recursive
- name: mrs_uav_status
  type: git
  repo: https://github.com/ctu-mrs/mrs_uav_status.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_uav_status
  scripts:
  - git submodule update --init --recursive
- name: mrs_uav_testing
  type: git
  repo: https://github.com/ctu-mrs/mrs_uav_testing.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_uav_testing
  scripts:
  - git submodule update --init --recursive
- name: mrs_uav_trackers
  type: git
  repo: https://github.com/ctu-mrs/mrs_uav_trackers.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_uav_trackers
  scripts:
  - git submodule update --init --recursive
- name: tmux
  type: git
  repo: https://github.com/tmux/tmux.git
  sparse_paths:
  -
  rev: 3.0a
  link: utils/tmux
  scripts:
  - git submodule update --init --recursive
- name: tmuxinator
  type: git
  repo: https://github.com/tmuxinator/tmuxinator.git
  sparse_paths:
  -
  rev: v2.0.0
  link: utils/tmuxinator
  scripts:
  - git submodule update --init --recursive
sources_locked:
- name: mrs_bumper
  type: git
  repo: https://github.com/ctu-mrs/mrs_bumper.git
  sparse_paths:
  -
  rev: 7c8c9a24f6d11e30c1c6f40dfcbe6890fdb56372
  link: ros_packages/mrs_bumper
  scripts:
  - git submodule update --init --recursive
- name: mrs_lib
  type: git
  repo: https://github.com/ctu-mrs/mrs_lib.git
  sparse_paths:
  -
  rev: c8057b90f1504336811ab9c0309b6c9b125059c2
  link: ros_packages/mrs_lib
  scripts:
  - git submodule update --init --recursive
- name: mrs_mavros_interface
  type: git
  repo: https://github.com/ctu-mrs/mrs_mavros_interface.git
  sparse_paths:
  -
  rev: bbe775f5d429a7fa0d2ba2a9ffa2ebed3eca9446
  link: ros_packages/mrs_mavros_interface
  scripts:
  - git submodule update --init --recursive
- name: mrs_msgs
  type: git
  repo: https://github.com/ctu-mrs/mrs_msgs.git
  sparse_paths:
  -
  rev: 9f35427fa749bfa39907bb6db28459c2ecfa168f
  link: ros_packages/mrs_msgs
  scripts:
  - git submodule update --init --recursive
- name: mrs_optic_flow
  type: git
  repo: https://github.com/ctu-mrs/mrs_optic_flow.git
  sparse_paths:
  -
  rev: 76168c42d70b7394bb160e7d92029888d9811375
  link: ros_packages/mrs_optic_flow
  scripts:
  - git submodule update --init --recursive
- name: mrs_uav_controllers
  type: git
  repo: https://github.com/ctu-mrs/mrs_uav_controllers.git
  sparse_paths:
  -
  rev: f8b15082e07a21b2f868a0404ac07dc4eccdef05
  link: ros_packages/mrs_uav_controllers
  scripts:
  - git submodule update --init --recursive
- name: mrs_uav_general
  type: git
  repo: https://github.com/ctu-mrs/mrs_uav_general.git
  sparse_paths:
  -
  rev: 598649d19f6d50d63ae05111a1d9f980be97c2c8
  link: ros_packages/mrs_uav_general
  scripts:
  - git submodule update --init --recursive
- name: mrs_uav_managers
  type: git
  repo: https://github.com/ctu-mrs/mrs_uav_managers.git
  sparse_paths:
  -
  rev: cfc33398e84bbe110d1f11cac7a6e0db49349d84
  link: ros_packages/mrs_uav_managers
  scripts:
  - git submodule update --init --recursive
- name: mrs_uav_odometry
  type: git
  repo: https://github.com/ctu-mrs/mrs_uav_odometry.git
  sparse_paths:
  -
  rev: d3dcfdf3e3a29f8d0fb69cc96ed3cd2b5e210739
  link: ros_packages/mrs_uav_odometry
  scripts:
  - git submodule update --init --recursive
- name: mrs_uav_status
  type: git
  repo: https://github.com/ctu-mrs/mrs_uav_status.git
  sparse_paths:
  -
  rev: 95dc8fee4d27023a9123e94ad358c06f435bd04b
  link: ros_packages/mrs_uav_status
  scripts:
  - git submodule update --init --recursive
- name: mrs_uav_testing
  type: git
  repo: https://github.com/ctu-mrs/mrs_uav_testing.git
  sparse_paths:
  -
  rev: 6b82ca44f3a0afd2ec2417dbd3d445f77335b1a8
  link: ros_packages/mrs_uav_testing
  scripts:
  - git submodule update --init --recursive
- name: mrs_uav_trackers
  type: git
  repo: https://github.com/ctu-mrs/mrs_uav_trackers.git
  sparse_paths:
  -
  rev: 927b2b4de3294171ee290672b2f05dca49414259
  link: ros_packages/mrs_uav_trackers
  scripts:
  - git submodule update --init --recursive
- name: tmux
  type: git
  repo: https://github.com/tmux/tmux.git
  sparse_paths:
  -
  rev: 25ae02869544b84b639b25b0aa69baa6ea2d3a6a
  link: utils/tmux
  scripts:
  - git submodule update --init --recursive
- name: tmuxinator
  type: git
  repo: https://github.com/tmuxinator/tmuxinator.git
  sparse_paths:
  -
  rev: 7208ab2ed7c8cfbcbe92c4b0db2bc01550d40fd4
  link: utils/tmuxinator
  scripts:
  - git submodule update --init --recursive
