location: .gitman
sources:
- name: mavlink-gbp-release
  type: git
  repo: https://github.com/mavlink/mavlink-gbp-release
  sparse_paths:
  -
  rev: a131e4bd665d2dc7f822797faf13d783fcd4bb8a
  link: lib/mavlink-gbp-release
  scripts:
  - git submodule update --init --recursive
- name: mavros
  type: git
  repo: git@mrs.felk.cvut.cz:uav/mavros.git
  sparse_paths:
  -
  rev: header_fix
  link: ros_packages/mavros
  scripts:
  - git submodule update --init --recursive
- name: mrs_controllers
  type: git
  repo: git@mrs.felk.cvut.cz:uav/core/mrs_controllers.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_controllers
  scripts:
  - git submodule update --init --recursive
- name: mrs_general
  type: git
  repo: git@mrs.felk.cvut.cz:uav/core/mrs_general.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_general
  scripts:
  - git submodule update --init --recursive
- name: mrs_lib
  type: git
  repo: git@mrs.felk.cvut.cz:uav/utils/mrs_lib.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_lib
  scripts:
  - git submodule update --init --recursive
- name: mrs_mavros_interface
  type: git
  repo: git@mrs.felk.cvut.cz:uav/core/mrs_mavros_interface.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_mavros_interface
  scripts:
  - git submodule update --init --recursive
- name: mrs_msgs
  type: git
  repo: git@mrs.felk.cvut.cz:uav/core/mrs_msgs.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_msgs
  scripts:
  - git submodule update --init --recursive
- name: mrs_odometry
  type: git
  repo: git@mrs.felk.cvut.cz:uav/core/mrs_odometry.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_odometry
  scripts:
  - git submodule update --init --recursive
- name: mrs_optic_flow
  type: git
  repo: git@mrs.felk.cvut.cz:uav/core/mrs_optic_flow.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_optic_flow
  scripts:
  - git submodule update --init --recursive
- name: mrs_status
  type: git
  repo: git@mrs.felk.cvut.cz:uav/utils/mrs_status.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_status
  scripts:
  - git submodule update --init --recursive
- name: mrs_trackers
  type: git
  repo: git@mrs.felk.cvut.cz:uav/core/mrs_trackers.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_trackers
  scripts:
  - git submodule update --init --recursive
- name: mrs_uav_manager
  type: git
  repo: git@mrs.felk.cvut.cz:uav/core/mrs_uav_manager.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_uav_manager
  scripts:
  - git submodule update --init --recursive
sources_locked:
- name: mavlink-gbp-release
  type: git
  repo: https://github.com/mavlink/mavlink-gbp-release
  sparse_paths:
  -
  rev: a131e4bd665d2dc7f822797faf13d783fcd4bb8a
  link: lib/mavlink-gbp-release
  scripts:
  - git submodule update --init --recursive
- name: mavros
  type: git
  repo: git@mrs.felk.cvut.cz:uav/mavros.git
  sparse_paths:
  -
  rev: 0cf50af8dfcf32b320bfb4b8b7630e500b569af9
  link: ros_packages/mavros
  scripts:
  - git submodule update --init --recursive
- name: mrs_controllers
  type: git
  repo: git@mrs.felk.cvut.cz:uav/core/mrs_controllers.git
  sparse_paths:
  -
  rev: e9cae69cf494d3c26a63d07332ac56271a712c61
  link: ros_packages/mrs_controllers
  scripts:
  - git submodule update --init --recursive
- name: mrs_general
  type: git
  repo: git@mrs.felk.cvut.cz:uav/core/mrs_general.git
  sparse_paths:
  -
  rev: fb1885c978ecbbf4facb795f2b73fc17ff504604
  link: ros_packages/mrs_general
  scripts:
  - git submodule update --init --recursive
- name: mrs_lib
  type: git
  repo: git@mrs.felk.cvut.cz:uav/utils/mrs_lib.git
  sparse_paths:
  -
  rev: c8bb286fb427f686d93096213c6fc6ea719b8c79
  link: ros_packages/mrs_lib
  scripts:
  - git submodule update --init --recursive
- name: mrs_mavros_interface
  type: git
  repo: git@mrs.felk.cvut.cz:uav/core/mrs_mavros_interface.git
  sparse_paths:
  -
  rev: e35e8783965aca67c882d0385a2c008ff099e653
  link: ros_packages/mrs_mavros_interface
  scripts:
  - git submodule update --init --recursive
- name: mrs_msgs
  type: git
  repo: git@mrs.felk.cvut.cz:uav/core/mrs_msgs.git
  sparse_paths:
  -
  rev: e458d51f8dedbbfeb6de21835d8cc1fc2e8044a8
  link: ros_packages/mrs_msgs
  scripts:
  - git submodule update --init --recursive
- name: mrs_odometry
  type: git
  repo: git@mrs.felk.cvut.cz:uav/core/mrs_odometry.git
  sparse_paths:
  -
  rev: 5c6da1e3f7eb0d599c773bb2f6957b441a6e84b2
  link: ros_packages/mrs_odometry
  scripts:
  - git submodule update --init --recursive
- name: mrs_optic_flow
  type: git
  repo: git@mrs.felk.cvut.cz:uav/core/mrs_optic_flow.git
  sparse_paths:
  -
  rev: b611d156917b09687dd3b75b834656b123aae228
  link: ros_packages/mrs_optic_flow
  scripts:
  - git submodule update --init --recursive
- name: mrs_status
  type: git
  repo: git@mrs.felk.cvut.cz:uav/utils/mrs_status.git
  sparse_paths:
  -
  rev: 44f1d692876e6a731ff95f60ddfb2189722db14c
  link: ros_packages/mrs_status
  scripts:
  - git submodule update --init --recursive
- name: mrs_trackers
  type: git
  repo: git@mrs.felk.cvut.cz:uav/core/mrs_trackers.git
  sparse_paths:
  -
  rev: ce1b99648c7c9199f70825d1a01355a5f8d91301
  link: ros_packages/mrs_trackers
  scripts:
  - git submodule update --init --recursive
- name: mrs_uav_manager
  type: git
  repo: git@mrs.felk.cvut.cz:uav/core/mrs_uav_manager.git
  sparse_paths:
  -
  rev: da33fa0750e87ce3fedf9fe08c062c1ba6d10eb5
  link: ros_packages/mrs_uav_manager
  scripts:
  - git submodule update --init --recursive
