location: .gitman
sources:
  - repo: https://github.com/mavlink/mavlink-gbp-release
    name: mavlink-gbp-release
    rev: 0dc40a07d97e665c563600081840c45b60bae1cf
    type: git
    sparse_paths:
      -
    link: lib/mavlink-gbp-release
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mavros
    name: mavros
    rev: added_dialect_file
    type: git
    sparse_paths:
      -
    link: ros_packages/mavros
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_bumper.git
    name: mrs_bumper
    rev: master
    type: git
    sparse_paths:
      -
    link: ros_packages/mrs_bumper
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_lib.git
    name: mrs_lib
    rev: master
    type: git
    sparse_paths:
      -
    link: ros_packages/mrs_lib
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_mavros_interface.git
    name: mrs_mavros_interface
    rev: master
    type: git
    sparse_paths:
      -
    link: ros_packages/mrs_mavros_interface
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_msgs.git
    name: mrs_msgs
    rev: master
    type: git
    sparse_paths:
      -
    link: ros_packages/mrs_msgs
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_rviz_plugins.git
    name: mrs_rviz_plugins
    rev: master
    type: git
    sparse_paths:
      -
    link: ros_packages/mrs_rviz_plugins
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_controllers.git
    name: mrs_uav_controllers
    rev: master
    type: git
    sparse_paths:
      -
    link: ros_packages/mrs_uav_controllers
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_general.git
    name: mrs_uav_general
    rev: master
    type: git
    sparse_paths:
      -
    link: ros_packages/mrs_uav_general
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_managers.git
    name: mrs_uav_managers
    rev: master
    type: git
    sparse_paths:
      -
    link: ros_packages/mrs_uav_managers
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_odometry.git
    name: mrs_uav_odometry
    rev: master
    type: git
    sparse_paths:
      -
    link: ros_packages/mrs_uav_odometry
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_status.git
    name: mrs_uav_status
    rev: master
    type: git
    sparse_paths:
      -
    link: ros_packages/mrs_uav_status
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_testing.git
    name: mrs_uav_testing
    rev: master
    type: git
    sparse_paths:
      -
    link: ros_packages/mrs_uav_testing
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_trackers.git
    name: mrs_uav_trackers
    rev: master
    type: git
    sparse_paths:
      -
    link: ros_packages/mrs_uav_trackers
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_trajectory_generation
    name: mrs_uav_trajectory_generation
    rev: master
    type: git
    sparse_paths:
      -
    link: ros_packages/mrs_uav_trajectory_generation
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/nlopt_ros
    name: nlopt_ros
    rev: master
    type: git
    sparse_paths:
      -
    link: ros_packages/thirdparty/nlopt_ros
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/nodelet_core
    name: nodelet_core
    rev: callback_fix
    type: git
    sparse_paths:
      -
    link: ros_packages/thirdparty/nodelet_core
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/tmux/tmux.git
    name: tmux
    rev: 3.0a
    type: git
    sparse_paths:
      -
    link: utils/tmux
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/tmuxinator/tmuxinator.git
    name: tmuxinator
    rev: v2.0.0
    type: git
    sparse_paths:
      -
    link: utils/tmuxinator
    links:
      -
    scripts:
      - git submodule update --init --recursive
sources_locked:
  - repo: https://github.com/mavlink/mavlink-gbp-release
    name: mavlink-gbp-release
    rev: 0dc40a07d97e665c563600081840c45b60bae1cf
    type: git
    sparse_paths:
      -
    link: lib/mavlink-gbp-release
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mavros
    name: mavros
    rev: 8deab345e2560245c021b772cf675a9be54cee04
    type: git
    sparse_paths:
      -
    link: ros_packages/mavros
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_bumper.git
    name: mrs_bumper
    rev: da8d0c8c226f34ae1f5602fbd78a2609925b9478
    type: git
    sparse_paths:
      -
    link: ros_packages/mrs_bumper
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_lib.git
    name: mrs_lib
    rev: 9df3dc0c22f687f74e938929de7f1b7d5ef3b418
    type: git
    sparse_paths:
      -
    link: ros_packages/mrs_lib
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_mavros_interface.git
    name: mrs_mavros_interface
    rev: ecbcfe2357d11d176fc10b2ff7cb06accb36a86f
    type: git
    sparse_paths:
      -
    link: ros_packages/mrs_mavros_interface
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_msgs.git
    name: mrs_msgs
    rev: 51728c766a7605256ed3794fd773bbc7af1c3466
    type: git
    sparse_paths:
      -
    link: ros_packages/mrs_msgs
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_rviz_plugins.git
    name: mrs_rviz_plugins
    rev: 7220c30c394920a57c490223e186ffc1cfd13e66
    type: git
    sparse_paths:
      -
    link: ros_packages/mrs_rviz_plugins
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_controllers.git
    name: mrs_uav_controllers
    rev: 5f65c5efa1d011bbaa0b37447058e4de280392c5
    type: git
    sparse_paths:
      -
    link: ros_packages/mrs_uav_controllers
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_general.git
    name: mrs_uav_general
    rev: 6048ed20672573cc4102ccef19d07082c6f4d457
    type: git
    sparse_paths:
      -
    link: ros_packages/mrs_uav_general
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_managers.git
    name: mrs_uav_managers
    rev: c59ba5d6ea3114c6a8afe66c731f10d550a1a366
    type: git
    sparse_paths:
      -
    link: ros_packages/mrs_uav_managers
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_odometry.git
    name: mrs_uav_odometry
    rev: 0b8d62b83d64927e6d513f98ef314f10c2446174
    type: git
    sparse_paths:
      -
    link: ros_packages/mrs_uav_odometry
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_status.git
    name: mrs_uav_status
    rev: 9fe9b7ad168597a224b28e8f045542152526182c
    type: git
    sparse_paths:
      -
    link: ros_packages/mrs_uav_status
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_testing.git
    name: mrs_uav_testing
    rev: ccbf6fb9cde2b514597140b52387d9703d7eab8b
    type: git
    sparse_paths:
      -
    link: ros_packages/mrs_uav_testing
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_trackers.git
    name: mrs_uav_trackers
    rev: 1c882edce1b27bc64456a53c3346c1f4c88bea72
    type: git
    sparse_paths:
      -
    link: ros_packages/mrs_uav_trackers
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_trajectory_generation
    name: mrs_uav_trajectory_generation
    rev: 85d601abacf9cc3203ef838285a6a73b9ba04ea8
    type: git
    sparse_paths:
      -
    link: ros_packages/mrs_uav_trajectory_generation
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/nlopt_ros
    name: nlopt_ros
    rev: 5e351e81e8ee0c39d3096f38a0aa990304298631
    type: git
    sparse_paths:
      -
    link: ros_packages/thirdparty/nlopt_ros
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/nodelet_core
    name: nodelet_core
    rev: b4344e75e9afa93010ffc20c3918ecfbab1848e4
    type: git
    sparse_paths:
      -
    link: ros_packages/thirdparty/nodelet_core
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/tmux/tmux.git
    name: tmux
    rev: 25ae02869544b84b639b25b0aa69baa6ea2d3a6a
    type: git
    sparse_paths:
      -
    link: utils/tmux
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/tmuxinator/tmuxinator.git
    name: tmuxinator
    rev: 7208ab2ed7c8cfbcbe92c4b0db2bc01550d40fd4
    type: git
    sparse_paths:
      -
    link: utils/tmuxinator
    links:
      -
    scripts:
      - git submodule update --init --recursive
groups:
  -
default_group: ''
