location: .gitman
sources:
- name: mavlink-gbp-release
  type: git
  repo: https://github.com/mavlink/mavlink-gbp-release
  sparse_paths:
  -
  rev: a131e4bd665d2dc7f822797faf13d783fcd4bb8a
  link: lib/mavlink-gbp-release
  scripts:
  - git submodule update --init --recursive
- name: mavros
  type: git
  repo: git@mrs.felk.cvut.cz:uav/mavros.git
  sparse_paths:
  -
  rev: 0.30.0
  link: ros_packages/mavros
  scripts:
  - git submodule update --init --recursive
- name: mrs_controllers
  type: git
  repo: git@mrs.felk.cvut.cz:uav/core/mrs_controllers.git
  sparse_paths:
  -
  rev: launch_files
  link: ros_packages/mrs_controllers
  scripts:
  - git submodule update --init --recursive
- name: mrs_general
  type: git
  repo: git@mrs.felk.cvut.cz:uav/core/mrs_general.git
  sparse_paths:
  -
  rev: launch_files
  link: ros_packages/mrs_general
  scripts:
  - git submodule update --init --recursive
- name: mrs_lib
  type: git
  repo: git@mrs.felk.cvut.cz:uav/utils/mrs_lib.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_lib
  scripts:
  - git submodule update --init --recursive
- name: mrs_mavros_interface
  type: git
  repo: git@mrs.felk.cvut.cz:uav/core/mrs_mavros_interface.git
  sparse_paths:
  -
  rev: launch_files
  link: ros_packages/mrs_mavros_interface
  scripts:
  - git submodule update --init --recursive
- name: mrs_msgs
  type: git
  repo: git@mrs.felk.cvut.cz:uav/core/mrs_msgs.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_msgs
  scripts:
  - git submodule update --init --recursive
- name: mrs_odometry
  type: git
  repo: git@mrs.felk.cvut.cz:uav/core/mrs_odometry.git
  sparse_paths:
  -
  rev: launch_files
  link: ros_packages/mrs_odometry
  scripts:
  - git submodule update --init --recursive
- name: mrs_optic_flow
  type: git
  repo: git@mrs.felk.cvut.cz:uav/core/mrs_optic_flow.git
  sparse_paths:
  -
  rev: launch_files
  link: ros_packages/mrs_optic_flow
  scripts:
  - git submodule update --init --recursive
- name: mrs_status
  type: git
  repo: git@mrs.felk.cvut.cz:uav/utils/mrs_status.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_status
  scripts:
  - git submodule update --init --recursive
- name: mrs_trackers
  type: git
  repo: git@mrs.felk.cvut.cz:uav/core/mrs_trackers.git
  sparse_paths:
  -
  rev: launch_files
  link: ros_packages/mrs_trackers
  scripts:
  - git submodule update --init --recursive
- name: mrs_uav_manager
  type: git
  repo: git@mrs.felk.cvut.cz:uav/core/mrs_uav_manager.git
  sparse_paths:
  -
  rev: launch_files
  link: ros_packages/mrs_uav_manager
  scripts:
  - git submodule update --init --recursive
sources_locked:
- name: mavlink-gbp-release
  type: git
  repo: https://github.com/mavlink/mavlink-gbp-release
  sparse_paths:
  -
  rev: a131e4bd665d2dc7f822797faf13d783fcd4bb8a
  link: lib/mavlink-gbp-release
  scripts:
  - git submodule update --init --recursive
- name: mavros
  type: git
  repo: git@mrs.felk.cvut.cz:uav/mavros.git
  sparse_paths:
  -
  rev: e6fd4513e610bec82a7dbbfbaa72947ee4e94121
  link: ros_packages/mavros
  scripts:
  - git submodule update --init --recursive
- name: mrs_controllers
  type: git
  repo: git@mrs.felk.cvut.cz:uav/core/mrs_controllers.git
  sparse_paths:
  -
  rev: 2059b14da3a35fd91c622d93f549aa11a3b31885
  link: ros_packages/mrs_controllers
  scripts:
  - git submodule update --init --recursive
- name: mrs_general
  type: git
  repo: git@mrs.felk.cvut.cz:uav/core/mrs_general.git
  sparse_paths:
  -
  rev: 8011f94b6e0b2dd21b7acfed6eca12d131f7609d
  link: ros_packages/mrs_general
  scripts:
  - git submodule update --init --recursive
- name: mrs_lib
  type: git
  repo: git@mrs.felk.cvut.cz:uav/utils/mrs_lib.git
  sparse_paths:
  -
  rev: a4d124496ff8148f7f58bd297c8e7ed4eaa5f013
  link: ros_packages/mrs_lib
  scripts:
  - git submodule update --init --recursive
- name: mrs_mavros_interface
  type: git
  repo: git@mrs.felk.cvut.cz:uav/core/mrs_mavros_interface.git
  sparse_paths:
  -
  rev: 008be1f89b4fa2ce55ccbd128842a1fe5dbeef0f
  link: ros_packages/mrs_mavros_interface
  scripts:
  - git submodule update --init --recursive
- name: mrs_msgs
  type: git
  repo: git@mrs.felk.cvut.cz:uav/core/mrs_msgs.git
  sparse_paths:
  -
  rev: a14ea83d9f2f1cc6b1909c99b4cf636787340466
  link: ros_packages/mrs_msgs
  scripts:
  - git submodule update --init --recursive
- name: mrs_odometry
  type: git
  repo: git@mrs.felk.cvut.cz:uav/core/mrs_odometry.git
  sparse_paths:
  -
  rev: 2189738ce6e791a2e3fe32261104b0fc99169584
  link: ros_packages/mrs_odometry
  scripts:
  - git submodule update --init --recursive
- name: mrs_optic_flow
  type: git
  repo: git@mrs.felk.cvut.cz:uav/core/mrs_optic_flow.git
  sparse_paths:
  -
  rev: 188b66532b6d96e9bdfc4ea8e1d04ccd0afcecf0
  link: ros_packages/mrs_optic_flow
  scripts:
  - git submodule update --init --recursive
- name: mrs_status
  type: git
  repo: git@mrs.felk.cvut.cz:uav/utils/mrs_status.git
  sparse_paths:
  -
  rev: e308433af2d11586f26f1bfb504a3c636eb55404
  link: ros_packages/mrs_status
  scripts:
  - git submodule update --init --recursive
- name: mrs_trackers
  type: git
  repo: git@mrs.felk.cvut.cz:uav/core/mrs_trackers.git
  sparse_paths:
  -
  rev: 109670269e5725a9abdf4d663330d071b85cfd16
  link: ros_packages/mrs_trackers
  scripts:
  - git submodule update --init --recursive
- name: mrs_uav_manager
  type: git
  repo: git@mrs.felk.cvut.cz:uav/core/mrs_uav_manager.git
  sparse_paths:
  -
  rev: 7e64e3a00efaf4e9a5605d8b441358b8bb5b1477
  link: ros_packages/mrs_uav_manager
  scripts:
  - git submodule update --init --recursive
