location: .gitman
sources:
- name: mavlink-gbp-release
  type: git
  repo: https://github.com/mavlink/mavlink-gbp-release
  sparse_paths:
  -
  rev: a131e4bd665d2dc7f822797faf13d783fcd4bb8a
  link: lib/mavlink-gbp-release
  scripts:
  - git submodule update --init --recursive
- name: mavros
  type: git
  repo: git@mrs.felk.cvut.cz:uav/mavros.git
  sparse_paths:
  -
  rev: header_fix
  link: ros_packages/mavros
  scripts:
  - git submodule update --init --recursive
- name: mrs_controllers
  type: git
  repo: git@mrs.felk.cvut.cz:uav/core/mrs_controllers.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_controllers
  scripts:
  - git submodule update --init --recursive
- name: mrs_general
  type: git
  repo: git@mrs.felk.cvut.cz:uav/core/mrs_general.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_general
  scripts:
  - git submodule update --init --recursive
- name: mrs_lib
  type: git
  repo: git@mrs.felk.cvut.cz:uav/utils/mrs_lib.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_lib
  scripts:
  - git submodule update --init --recursive
- name: mrs_mavros_interface
  type: git
  repo: git@mrs.felk.cvut.cz:uav/core/mrs_mavros_interface.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_mavros_interface
  scripts:
  - git submodule update --init --recursive
- name: mrs_msgs
  type: git
  repo: git@mrs.felk.cvut.cz:uav/core/mrs_msgs.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_msgs
  scripts:
  - git submodule update --init --recursive
- name: mrs_odometry
  type: git
  repo: git@mrs.felk.cvut.cz:uav/core/mrs_odometry.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_odometry
  scripts:
  - git submodule update --init --recursive
- name: mrs_optic_flow
  type: git
  repo: git@mrs.felk.cvut.cz:uav/core/mrs_optic_flow.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_optic_flow
  scripts:
  - git submodule update --init --recursive
- name: mrs_status
  type: git
  repo: git@mrs.felk.cvut.cz:uav/utils/mrs_status.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_status
  scripts:
  - git submodule update --init --recursive
- name: mrs_trackers
  type: git
  repo: git@mrs.felk.cvut.cz:uav/core/mrs_trackers.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_trackers
  scripts:
  - git submodule update --init --recursive
- name: mrs_uav_manager
  type: git
  repo: git@mrs.felk.cvut.cz:uav/core/mrs_uav_manager.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_uav_manager
  scripts:
  - git submodule update --init --recursive
sources_locked:
- name: mavlink-gbp-release
  type: git
  repo: https://github.com/mavlink/mavlink-gbp-release
  sparse_paths:
  -
  rev: a131e4bd665d2dc7f822797faf13d783fcd4bb8a
  link: lib/mavlink-gbp-release
  scripts:
  - git submodule update --init --recursive
- name: mavros
  type: git
  repo: git@mrs.felk.cvut.cz:uav/mavros.git
  sparse_paths:
  -
  rev: 0cf50af8dfcf32b320bfb4b8b7630e500b569af9
  link: ros_packages/mavros
  scripts:
  - git submodule update --init --recursive
- name: mrs_controllers
  type: git
  repo: git@mrs.felk.cvut.cz:uav/core/mrs_controllers.git
  sparse_paths:
  -
  rev: e9cae69cf494d3c26a63d07332ac56271a712c61
  link: ros_packages/mrs_controllers
  scripts:
  - git submodule update --init --recursive
- name: mrs_general
  type: git
  repo: git@mrs.felk.cvut.cz:uav/core/mrs_general.git
  sparse_paths:
  -
  rev: 0f5ace3e0d8fefd0cd69463487166759788a39d0
  link: ros_packages/mrs_general
  scripts:
  - git submodule update --init --recursive
- name: mrs_lib
  type: git
  repo: git@mrs.felk.cvut.cz:uav/utils/mrs_lib.git
  sparse_paths:
  -
  rev: ba9b352018d46afb2b48eac7d70935e0cb4aae5c
  link: ros_packages/mrs_lib
  scripts:
  - git submodule update --init --recursive
- name: mrs_mavros_interface
  type: git
  repo: git@mrs.felk.cvut.cz:uav/core/mrs_mavros_interface.git
  sparse_paths:
  -
  rev: e35e8783965aca67c882d0385a2c008ff099e653
  link: ros_packages/mrs_mavros_interface
  scripts:
  - git submodule update --init --recursive
- name: mrs_msgs
  type: git
  repo: git@mrs.felk.cvut.cz:uav/core/mrs_msgs.git
  sparse_paths:
  -
  rev: 6e2648d65ad14c27fba3f27d05913e5067a157ef
  link: ros_packages/mrs_msgs
  scripts:
  - git submodule update --init --recursive
- name: mrs_odometry
  type: git
  repo: git@mrs.felk.cvut.cz:uav/core/mrs_odometry.git
  sparse_paths:
  -
  rev: 7dc8361dc6f92f0485684ac5ce377f21b2601bea
  link: ros_packages/mrs_odometry
  scripts:
  - git submodule update --init --recursive
- name: mrs_optic_flow
  type: git
  repo: git@mrs.felk.cvut.cz:uav/core/mrs_optic_flow.git
  sparse_paths:
  -
  rev: b611d156917b09687dd3b75b834656b123aae228
  link: ros_packages/mrs_optic_flow
  scripts:
  - git submodule update --init --recursive
- name: mrs_status
  type: git
  repo: git@mrs.felk.cvut.cz:uav/utils/mrs_status.git
  sparse_paths:
  -
  rev: 9f334bdb74755b75f03e75140deaf1c7f7cbc490
  link: ros_packages/mrs_status
  scripts:
  - git submodule update --init --recursive
- name: mrs_trackers
  type: git
  repo: git@mrs.felk.cvut.cz:uav/core/mrs_trackers.git
  sparse_paths:
  -
  rev: 2ae929f79ddfba9bec43b39afdf351c1a37fe3a5
  link: ros_packages/mrs_trackers
  scripts:
  - git submodule update --init --recursive
- name: mrs_uav_manager
  type: git
  repo: git@mrs.felk.cvut.cz:uav/core/mrs_uav_manager.git
  sparse_paths:
  -
  rev: d0f068dcca5a6ed9b24b9e4df6e7b51ed91fdabc
  link: ros_packages/mrs_uav_manager
  scripts:
  - git submodule update --init --recursive
