location: .gitman
sources:
- name: mavlink-gbp-release
  type: git
  repo: https://github.com/mavlink/mavlink-gbp-release
  sparse_paths:
  -
  rev: 19c4fc6006d88636a5b8b5f2e608bfcdf80e6620
  link: lib/mavlink-gbp-release
  scripts:
  - git submodule update --init --recursive
- name: mavros
  type: git
  repo: https://github.com/ctu-mrs/mavros
  sparse_paths:
  -
  rev: added_dialect_file
  link: ros_packages/mavros
  scripts:
  - git submodule update --init --recursive
- name: mrs_bumper
  type: git
  repo: https://github.com/ctu-mrs/mrs_bumper.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_bumper
  scripts:
  - git submodule update --init --recursive
- name: mrs_lib
  type: git
  repo: https://github.com/ctu-mrs/mrs_lib.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_lib
  scripts:
  - git submodule update --init --recursive
- name: mrs_mavros_interface
  type: git
  repo: https://github.com/ctu-mrs/mrs_mavros_interface.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_mavros_interface
  scripts:
  - git submodule update --init --recursive
- name: mrs_msgs
  type: git
  repo: https://github.com/ctu-mrs/mrs_msgs.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_msgs
  scripts:
  - git submodule update --init --recursive
- name: mrs_rviz_plugins
  type: git
  repo: https://github.com/ctu-mrs/mrs_rviz_plugins.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_rviz_plugins
  scripts:
  - git submodule update --init --recursive
- name: mrs_uav_controllers
  type: git
  repo: https://github.com/ctu-mrs/mrs_uav_controllers.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_uav_controllers
  scripts:
  - git submodule update --init --recursive
- name: mrs_uav_general
  type: git
  repo: https://github.com/ctu-mrs/mrs_uav_general.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_uav_general
  scripts:
  - git submodule update --init --recursive
- name: mrs_uav_managers
  type: git
  repo: https://github.com/ctu-mrs/mrs_uav_managers.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_uav_managers
  scripts:
  - git submodule update --init --recursive
- name: mrs_uav_odometry
  type: git
  repo: https://github.com/ctu-mrs/mrs_uav_odometry.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_uav_odometry
  scripts:
  - git submodule update --init --recursive
- name: mrs_uav_status
  type: git
  repo: https://github.com/ctu-mrs/mrs_uav_status.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_uav_status
  scripts:
  - git submodule update --init --recursive
- name: mrs_uav_testing
  type: git
  repo: https://github.com/ctu-mrs/mrs_uav_testing.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_uav_testing
  scripts:
  - git submodule update --init --recursive
- name: mrs_uav_trackers
  type: git
  repo: https://github.com/ctu-mrs/mrs_uav_trackers.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_uav_trackers
  scripts:
  - git submodule update --init --recursive
- name: mrs_uav_trajectory_generation
  type: git
  repo: https://github.com/ctu-mrs/mrs_uav_trajectory_generation
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_uav_trajectory_generation
  scripts:
  - git submodule update --init --recursive
- name: nlopt_ros
  type: git
  repo: https://github.com/ctu-mrs/nlopt_ros
  sparse_paths:
  -
  rev: master
  link: ros_packages/thirdparty/nlopt_ros
  scripts:
  - git submodule update --init --recursive
- name: nodelet_core
  type: git
  repo: https://github.com/ctu-mrs/nodelet_core
  sparse_paths:
  -
  rev: callback_fix
  link: ros_packages/thirdparty/nodelet_core
  scripts:
  - git submodule update --init --recursive
- name: tmux
  type: git
  repo: https://github.com/tmux/tmux.git
  sparse_paths:
  -
  rev: 3.0a
  link: utils/tmux
  scripts:
  - git submodule update --init --recursive
- name: tmuxinator
  type: git
  repo: https://github.com/tmuxinator/tmuxinator.git
  sparse_paths:
  -
  rev: v2.0.0
  link: utils/tmuxinator
  scripts:
  - git submodule update --init --recursive
sources_locked:
- name: mavlink-gbp-release
  type: git
  repo: https://github.com/mavlink/mavlink-gbp-release
  sparse_paths:
  -
  rev: 19c4fc6006d88636a5b8b5f2e608bfcdf80e6620
  link: lib/mavlink-gbp-release
  scripts:
  - git submodule update --init --recursive
- name: mavros
  type: git
  repo: https://github.com/ctu-mrs/mavros
  sparse_paths:
  -
  rev: 8deab345e2560245c021b772cf675a9be54cee04
  link: ros_packages/mavros
  scripts:
  - git submodule update --init --recursive
- name: mrs_bumper
  type: git
  repo: https://github.com/ctu-mrs/mrs_bumper.git
  sparse_paths:
  -
  rev: 0775b23144b78d5196caf7849161ba374a278ec8
  link: ros_packages/mrs_bumper
  scripts:
  - git submodule update --init --recursive
- name: mrs_lib
  type: git
  repo: https://github.com/ctu-mrs/mrs_lib.git
  sparse_paths:
  -
  rev: d41a7da7a7c364e8772b7b4d77cd9417f1c41b9d
  link: ros_packages/mrs_lib
  scripts:
  - git submodule update --init --recursive
- name: mrs_mavros_interface
  type: git
  repo: https://github.com/ctu-mrs/mrs_mavros_interface.git
  sparse_paths:
  -
  rev: 51d67c4a1581fb6b74273cf5481b16178fb4eb71
  link: ros_packages/mrs_mavros_interface
  scripts:
  - git submodule update --init --recursive
- name: mrs_msgs
  type: git
  repo: https://github.com/ctu-mrs/mrs_msgs.git
  sparse_paths:
  -
  rev: a4b25acc6b0c6694a315fa2cc2c4eb6e2ab52ad4
  link: ros_packages/mrs_msgs
  scripts:
  - git submodule update --init --recursive
- name: mrs_rviz_plugins
  type: git
  repo: https://github.com/ctu-mrs/mrs_rviz_plugins.git
  sparse_paths:
  -
  rev: a67ea068656a659b968a0b029d98b24c574ba219
  link: ros_packages/mrs_rviz_plugins
  scripts:
  - git submodule update --init --recursive
- name: mrs_uav_controllers
  type: git
  repo: https://github.com/ctu-mrs/mrs_uav_controllers.git
  sparse_paths:
  -
  rev: e67dbc21def2fc012b61267c0e1fdd7261c1ff7e
  link: ros_packages/mrs_uav_controllers
  scripts:
  - git submodule update --init --recursive
- name: mrs_uav_general
  type: git
  repo: https://github.com/ctu-mrs/mrs_uav_general.git
  sparse_paths:
  -
  rev: eb2481a827d784216fee8dd00a4370d13e6d2e87
  link: ros_packages/mrs_uav_general
  scripts:
  - git submodule update --init --recursive
- name: mrs_uav_managers
  type: git
  repo: https://github.com/ctu-mrs/mrs_uav_managers.git
  sparse_paths:
  -
  rev: 9949864e30fd5a03dfc4b47b1f19c2338093f49a
  link: ros_packages/mrs_uav_managers
  scripts:
  - git submodule update --init --recursive
- name: mrs_uav_odometry
  type: git
  repo: https://github.com/ctu-mrs/mrs_uav_odometry.git
  sparse_paths:
  -
  rev: 76e998ce05e24727a58eacb76bae9cf7be5940c0
  link: ros_packages/mrs_uav_odometry
  scripts:
  - git submodule update --init --recursive
- name: mrs_uav_status
  type: git
  repo: https://github.com/ctu-mrs/mrs_uav_status.git
  sparse_paths:
  -
  rev: cc6fe6505f37713b9da59f4b29ee7d68509ddc26
  link: ros_packages/mrs_uav_status
  scripts:
  - git submodule update --init --recursive
- name: mrs_uav_testing
  type: git
  repo: https://github.com/ctu-mrs/mrs_uav_testing.git
  sparse_paths:
  -
  rev: d6ffe3dd7d4ec80bd60d5d9b0182861ff890cb68
  link: ros_packages/mrs_uav_testing
  scripts:
  - git submodule update --init --recursive
- name: mrs_uav_trackers
  type: git
  repo: https://github.com/ctu-mrs/mrs_uav_trackers.git
  sparse_paths:
  -
  rev: 96a2cfec09832f9299c1e0426bd193cb72c2f0c4
  link: ros_packages/mrs_uav_trackers
  scripts:
  - git submodule update --init --recursive
- name: mrs_uav_trajectory_generation
  type: git
  repo: https://github.com/ctu-mrs/mrs_uav_trajectory_generation
  sparse_paths:
  -
  rev: 572196e5f55c7e4fee3ca934aaeab3821521f67c
  link: ros_packages/mrs_uav_trajectory_generation
  scripts:
  - git submodule update --init --recursive
- name: nlopt_ros
  type: git
  repo: https://github.com/ctu-mrs/nlopt_ros
  sparse_paths:
  -
  rev: 5e351e81e8ee0c39d3096f38a0aa990304298631
  link: ros_packages/thirdparty/nlopt_ros
  scripts:
  - git submodule update --init --recursive
- name: nodelet_core
  type: git
  repo: https://github.com/ctu-mrs/nodelet_core
  sparse_paths:
  -
  rev: b4344e75e9afa93010ffc20c3918ecfbab1848e4
  link: ros_packages/thirdparty/nodelet_core
  scripts:
  - git submodule update --init --recursive
- name: tmux
  type: git
  repo: https://github.com/tmux/tmux.git
  sparse_paths:
  -
  rev: 25ae02869544b84b639b25b0aa69baa6ea2d3a6a
  link: utils/tmux
  scripts:
  - git submodule update --init --recursive
- name: tmuxinator
  type: git
  repo: https://github.com/tmuxinator/tmuxinator.git
  sparse_paths:
  -
  rev: 7208ab2ed7c8cfbcbe92c4b0db2bc01550d40fd4
  link: utils/tmuxinator
  scripts:
  - git submodule update --init --recursive
