location: .gitman
sources:
- name: mavlink-gbp-release
  type: git
  repo: https://github.com/mavlink/mavlink-gbp-release
  sparse_paths:
  -
  rev: a131e4bd665d2dc7f822797faf13d783fcd4bb8a
  link: lib/mavlink-gbp-release
  scripts:
  - git submodule update --init --recursive
- name: mavros
  type: git
  repo: git@mrs.felk.cvut.cz:uav/mavros.git
  sparse_paths:
  -
  rev: header_fix
  link: ros_packages/mavros
  scripts:
  - git submodule update --init --recursive
- name: mrs_controllers
  type: git
  repo: git@mrs.felk.cvut.cz:uav/core/mrs_controllers.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_controllers
  scripts:
  - git submodule update --init --recursive
- name: mrs_general
  type: git
  repo: git@mrs.felk.cvut.cz:uav/core/mrs_general.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_general
  scripts:
  - git submodule update --init --recursive
- name: mrs_lib
  type: git
  repo: git@mrs.felk.cvut.cz:uav/utils/mrs_lib.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_lib
  scripts:
  - git submodule update --init --recursive
- name: mrs_mavros_interface
  type: git
  repo: git@mrs.felk.cvut.cz:uav/core/mrs_mavros_interface.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_mavros_interface
  scripts:
  - git submodule update --init --recursive
- name: mrs_msgs
  type: git
  repo: git@mrs.felk.cvut.cz:uav/core/mrs_msgs.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_msgs
  scripts:
  - git submodule update --init --recursive
- name: mrs_odometry
  type: git
  repo: git@mrs.felk.cvut.cz:uav/core/mrs_odometry.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_odometry
  scripts:
  - git submodule update --init --recursive
- name: mrs_optic_flow
  type: git
  repo: git@mrs.felk.cvut.cz:uav/core/mrs_optic_flow.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_optic_flow
  scripts:
  - git submodule update --init --recursive
- name: mrs_status
  type: git
  repo: git@mrs.felk.cvut.cz:uav/utils/mrs_status.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_status
  scripts:
  - git submodule update --init --recursive
- name: mrs_trackers
  type: git
  repo: git@mrs.felk.cvut.cz:uav/core/mrs_trackers.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_trackers
  scripts:
  - git submodule update --init --recursive
- name: mrs_uav_manager
  type: git
  repo: git@mrs.felk.cvut.cz:uav/core/mrs_uav_manager.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_uav_manager
  scripts:
  - git submodule update --init --recursive
sources_locked:
- name: mavlink-gbp-release
  type: git
  repo: https://github.com/mavlink/mavlink-gbp-release
  sparse_paths:
  -
  rev: a131e4bd665d2dc7f822797faf13d783fcd4bb8a
  link: lib/mavlink-gbp-release
  scripts:
  - git submodule update --init --recursive
- name: mavros
  type: git
  repo: git@mrs.felk.cvut.cz:uav/mavros.git
  sparse_paths:
  -
  rev: 6fdf71bff442ea548806ee86e7c21f90dec70a03
  link: ros_packages/mavros
  scripts:
  - git submodule update --init --recursive
- name: mrs_controllers
  type: git
  repo: git@mrs.felk.cvut.cz:uav/core/mrs_controllers.git
  sparse_paths:
  -
  rev: c82b736ec499ee016deb6d665819824177f1c53f
  link: ros_packages/mrs_controllers
  scripts:
  - git submodule update --init --recursive
- name: mrs_general
  type: git
  repo: git@mrs.felk.cvut.cz:uav/core/mrs_general.git
  sparse_paths:
  -
  rev: 3ba8b9e8aa81b8bb6e85fe6ba2e4a094a3fdf641
  link: ros_packages/mrs_general
  scripts:
  - git submodule update --init --recursive
- name: mrs_lib
  type: git
  repo: git@mrs.felk.cvut.cz:uav/utils/mrs_lib.git
  sparse_paths:
  -
  rev: a2a72a70753ed02a0fc44a1c5142e04b389826db
  link: ros_packages/mrs_lib
  scripts:
  - git submodule update --init --recursive
- name: mrs_mavros_interface
  type: git
  repo: git@mrs.felk.cvut.cz:uav/core/mrs_mavros_interface.git
  sparse_paths:
  -
  rev: e35e8783965aca67c882d0385a2c008ff099e653
  link: ros_packages/mrs_mavros_interface
  scripts:
  - git submodule update --init --recursive
- name: mrs_msgs
  type: git
  repo: git@mrs.felk.cvut.cz:uav/core/mrs_msgs.git
  sparse_paths:
  -
  rev: e46b8a7096f651569b793723779dca95fbd47d34
  link: ros_packages/mrs_msgs
  scripts:
  - git submodule update --init --recursive
- name: mrs_odometry
  type: git
  repo: git@mrs.felk.cvut.cz:uav/core/mrs_odometry.git
  sparse_paths:
  -
  rev: 1077ddc80a2412a2c665ca563410ac874f3ddc47
  link: ros_packages/mrs_odometry
  scripts:
  - git submodule update --init --recursive
- name: mrs_optic_flow
  type: git
  repo: git@mrs.felk.cvut.cz:uav/core/mrs_optic_flow.git
  sparse_paths:
  -
  rev: 047462f6b643ac907a073498a0a201a9faef488e
  link: ros_packages/mrs_optic_flow
  scripts:
  - git submodule update --init --recursive
- name: mrs_status
  type: git
  repo: git@mrs.felk.cvut.cz:uav/utils/mrs_status.git
  sparse_paths:
  -
  rev: 187a191b27f5533bba2e281b2f5af5e6c6cbfcbe
  link: ros_packages/mrs_status
  scripts:
  - git submodule update --init --recursive
- name: mrs_trackers
  type: git
  repo: git@mrs.felk.cvut.cz:uav/core/mrs_trackers.git
  sparse_paths:
  -
  rev: f55c631698e2aae54dae40fb612d0e11bc05910c
  link: ros_packages/mrs_trackers
  scripts:
  - git submodule update --init --recursive
- name: mrs_uav_manager
  type: git
  repo: git@mrs.felk.cvut.cz:uav/core/mrs_uav_manager.git
  sparse_paths:
  -
  rev: cf1ee68a0dfeada62d7ad14a75ee4419d524e6a0
  link: ros_packages/mrs_uav_manager
  scripts:
  - git submodule update --init --recursive
