location: .gitman
sources:
- name: mavlink-gbp-release
  type: git
  repo: https://github.com/mavlink/mavlink-gbp-release
  sparse_paths:
  -
  rev: a131e4bd665d2dc7f822797faf13d783fcd4bb8a
  link: lib/mavlink-gbp-release
  scripts:
  - git submodule update --init --recursive
- name: mavros
  type: git
  repo: git@mrs.felk.cvut.cz:uav/mavros.git
  sparse_paths:
  -
  rev: header_fix
  link: ros_packages/mavros
  scripts:
  - git submodule update --init --recursive
- name: mrs_controllers
  type: git
  repo: git@mrs.felk.cvut.cz:uav/core/mrs_controllers.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_controllers
  scripts:
  - git submodule update --init --recursive
- name: mrs_general
  type: git
  repo: git@mrs.felk.cvut.cz:uav/core/mrs_general.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_general
  scripts:
  - git submodule update --init --recursive
- name: mrs_lib
  type: git
  repo: git@mrs.felk.cvut.cz:uav/utils/mrs_lib.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_lib
  scripts:
  - git submodule update --init --recursive
- name: mrs_mavros_interface
  type: git
  repo: git@mrs.felk.cvut.cz:uav/core/mrs_mavros_interface.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_mavros_interface
  scripts:
  - git submodule update --init --recursive
- name: mrs_msgs
  type: git
  repo: git@mrs.felk.cvut.cz:uav/core/mrs_msgs.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_msgs
  scripts:
  - git submodule update --init --recursive
- name: mrs_odometry
  type: git
  repo: git@mrs.felk.cvut.cz:uav/core/mrs_odometry.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_odometry
  scripts:
  - git submodule update --init --recursive
- name: mrs_optic_flow
  type: git
  repo: git@mrs.felk.cvut.cz:uav/core/mrs_optic_flow.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_optic_flow
  scripts:
  - git submodule update --init --recursive
- name: mrs_status
  type: git
  repo: git@mrs.felk.cvut.cz:uav/utils/mrs_status.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_status
  scripts:
  - git submodule update --init --recursive
- name: mrs_testing
  type: git
  repo: git@mrs.felk.cvut.cz:uav/utils/mrs_testing.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_testing
  scripts:
  - git submodule update --init --recursive
- name: mrs_trackers
  type: git
  repo: git@mrs.felk.cvut.cz:uav/core/mrs_trackers.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_trackers
  scripts:
  - git submodule update --init --recursive
- name: mrs_uav_manager
  type: git
  repo: git@mrs.felk.cvut.cz:uav/core/mrs_uav_manager.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_uav_manager
  scripts:
  - git submodule update --init --recursive
sources_locked:
- name: mavlink-gbp-release
  type: git
  repo: https://github.com/mavlink/mavlink-gbp-release
  sparse_paths:
  -
  rev: a131e4bd665d2dc7f822797faf13d783fcd4bb8a
  link: lib/mavlink-gbp-release
  scripts:
  - git submodule update --init --recursive
- name: mavros
  type: git
  repo: git@mrs.felk.cvut.cz:uav/mavros.git
  sparse_paths:
  -
  rev: 6fdf71bff442ea548806ee86e7c21f90dec70a03
  link: ros_packages/mavros
  scripts:
  - git submodule update --init --recursive
- name: mrs_controllers
  type: git
  repo: git@mrs.felk.cvut.cz:uav/core/mrs_controllers.git
  sparse_paths:
  -
  rev: 1d6f40635840a96b5f725a1bbbe3567178a61ac1
  link: ros_packages/mrs_controllers
  scripts:
  - git submodule update --init --recursive
- name: mrs_general
  type: git
  repo: git@mrs.felk.cvut.cz:uav/core/mrs_general.git
  sparse_paths:
  -
  rev: eddfa6fe444b7b973563f0cd08d051693fe70ccb
  link: ros_packages/mrs_general
  scripts:
  - git submodule update --init --recursive
- name: mrs_lib
  type: git
  repo: git@mrs.felk.cvut.cz:uav/utils/mrs_lib.git
  sparse_paths:
  -
  rev: b47e43727487ba5d891e07a8f2683738bd76955f
  link: ros_packages/mrs_lib
  scripts:
  - git submodule update --init --recursive
- name: mrs_mavros_interface
  type: git
  repo: git@mrs.felk.cvut.cz:uav/core/mrs_mavros_interface.git
  sparse_paths:
  -
  rev: 4f09909c1356a4fff765b8d28c46488c0e7527e2
  link: ros_packages/mrs_mavros_interface
  scripts:
  - git submodule update --init --recursive
- name: mrs_msgs
  type: git
  repo: git@mrs.felk.cvut.cz:uav/core/mrs_msgs.git
  sparse_paths:
  -
  rev: 1f41af27950e967757f3d2109c62861af6d45602
  link: ros_packages/mrs_msgs
  scripts:
  - git submodule update --init --recursive
- name: mrs_odometry
  type: git
  repo: git@mrs.felk.cvut.cz:uav/core/mrs_odometry.git
  sparse_paths:
  -
  rev: 9dbd7e31449a65fe4bca6af96d093f6b8adfc7e0
  link: ros_packages/mrs_odometry
  scripts:
  - git submodule update --init --recursive
- name: mrs_optic_flow
  type: git
  repo: git@mrs.felk.cvut.cz:uav/core/mrs_optic_flow.git
  sparse_paths:
  -
  rev: 3d56b369499c76b23f2fdb8fe0c796a623d64c12
  link: ros_packages/mrs_optic_flow
  scripts:
  - git submodule update --init --recursive
- name: mrs_status
  type: git
  repo: git@mrs.felk.cvut.cz:uav/utils/mrs_status.git
  sparse_paths:
  -
  rev: 8e556a7c9948f2b4f902ab09098e3e7a48487715
  link: ros_packages/mrs_status
  scripts:
  - git submodule update --init --recursive
- name: mrs_testing
  type: git
  repo: git@mrs.felk.cvut.cz:uav/utils/mrs_testing.git
  sparse_paths:
  -
  rev: 98d0fd8ab84c3793549ca454eb969bad34b7f223
  link: ros_packages/mrs_testing
  scripts:
  - git submodule update --init --recursive
- name: mrs_trackers
  type: git
  repo: git@mrs.felk.cvut.cz:uav/core/mrs_trackers.git
  sparse_paths:
  -
  rev: 7bf1714e046cc5a9aa79eff855942376b14604df
  link: ros_packages/mrs_trackers
  scripts:
  - git submodule update --init --recursive
- name: mrs_uav_manager
  type: git
  repo: git@mrs.felk.cvut.cz:uav/core/mrs_uav_manager.git
  sparse_paths:
  -
  rev: 09c965c6cdb5f5d0d7a59c504b85e7dbe9195711
  link: ros_packages/mrs_uav_manager
  scripts:
  - git submodule update --init --recursive
