location: .gitman
sources:
  - name: mavlink-gbp-release
    type: git
    repo: https://github.com/mavlink/mavlink-gbp-release
    sparse_paths:
      -
    rev: 0dc40a07d97e665c563600081840c45b60bae1cf
    link: lib/mavlink-gbp-release
    scripts:
      - git submodule update --init --recursive
  - name: mavros
    type: git
    repo: https://github.com/ctu-mrs/mavros
    sparse_paths:
      -
    rev: added_dialect_file
    link: ros_packages/mavros
    scripts:
      - git submodule update --init --recursive
  - name: mrs_bumper
    type: git
    repo: https://github.com/ctu-mrs/mrs_bumper.git
    sparse_paths:
      -
    rev: master
    link: ros_packages/mrs_bumper
    scripts:
      - git submodule update --init --recursive
  - name: mrs_lib
    type: git
    repo: https://github.com/ctu-mrs/mrs_lib.git
    sparse_paths:
      -
    rev: master
    link: ros_packages/mrs_lib
    scripts:
      - git submodule update --init --recursive
  - name: mrs_mavros_interface
    type: git
    repo: https://github.com/ctu-mrs/mrs_mavros_interface.git
    sparse_paths:
      -
    rev: master
    link: ros_packages/mrs_mavros_interface
    scripts:
      - git submodule update --init --recursive
  - name: mrs_msgs
    type: git
    repo: https://github.com/ctu-mrs/mrs_msgs.git
    sparse_paths:
      -
    rev: master
    link: ros_packages/mrs_msgs
    scripts:
      - git submodule update --init --recursive
  - name: mrs_rviz_plugins
    type: git
    repo: https://github.com/ctu-mrs/mrs_rviz_plugins.git
    sparse_paths:
      -
    rev: master
    link: ros_packages/mrs_rviz_plugins
    scripts:
      - git submodule update --init --recursive
  - name: mrs_uav_controllers
    type: git
    repo: https://github.com/ctu-mrs/mrs_uav_controllers.git
    sparse_paths:
      -
    rev: master
    link: ros_packages/mrs_uav_controllers
    scripts:
      - git submodule update --init --recursive
  - name: mrs_uav_general
    type: git
    repo: https://github.com/ctu-mrs/mrs_uav_general.git
    sparse_paths:
      -
    rev: master
    link: ros_packages/mrs_uav_general
    scripts:
      - git submodule update --init --recursive
  - name: mrs_uav_managers
    type: git
    repo: https://github.com/ctu-mrs/mrs_uav_managers.git
    sparse_paths:
      -
    rev: master
    link: ros_packages/mrs_uav_managers
    scripts:
      - git submodule update --init --recursive
  - name: mrs_uav_odometry
    type: git
    repo: https://github.com/ctu-mrs/mrs_uav_odometry.git
    sparse_paths:
      -
    rev: master
    link: ros_packages/mrs_uav_odometry
    scripts:
      - git submodule update --init --recursive
  - name: mrs_uav_status
    type: git
    repo: https://github.com/ctu-mrs/mrs_uav_status.git
    sparse_paths:
      -
    rev: master
    link: ros_packages/mrs_uav_status
    scripts:
      - git submodule update --init --recursive
  - name: mrs_uav_testing
    type: git
    repo: https://github.com/ctu-mrs/mrs_uav_testing.git
    sparse_paths:
      -
    rev: master
    link: ros_packages/mrs_uav_testing
    scripts:
      - git submodule update --init --recursive
  - name: mrs_uav_trackers
    type: git
    repo: https://github.com/ctu-mrs/mrs_uav_trackers.git
    sparse_paths:
      -
    rev: master
    link: ros_packages/mrs_uav_trackers
    scripts:
      - git submodule update --init --recursive
  - name: mrs_uav_trajectory_generation
    type: git
    repo: https://github.com/ctu-mrs/mrs_uav_trajectory_generation
    sparse_paths:
      -
    rev: master
    link: ros_packages/mrs_uav_trajectory_generation
    scripts:
      - git submodule update --init --recursive
  - name: nlopt_ros
    type: git
    repo: https://github.com/ctu-mrs/nlopt_ros
    sparse_paths:
      -
    rev: master
    link: ros_packages/thirdparty/nlopt_ros
    scripts:
      - git submodule update --init --recursive
  - name: nodelet_core
    type: git
    repo: https://github.com/ctu-mrs/nodelet_core
    sparse_paths:
      -
    rev: callback_fix
    link: ros_packages/thirdparty/nodelet_core
    scripts:
      - git submodule update --init --recursive
  - name: tmux
    type: git
    repo: https://github.com/tmux/tmux.git
    sparse_paths:
      -
    rev: 3.0a
    link: utils/tmux
    scripts:
      - git submodule update --init --recursive
  - name: tmuxinator
    type: git
    repo: https://github.com/tmuxinator/tmuxinator.git
    sparse_paths:
      -
    rev: v2.0.0
    link: utils/tmuxinator
    scripts:
      - git submodule update --init --recursive
sources_locked:
  - name: mavlink-gbp-release
    type: git
    repo: https://github.com/mavlink/mavlink-gbp-release
    sparse_paths:
      -
    rev: 0dc40a07d97e665c563600081840c45b60bae1cf
    link: lib/mavlink-gbp-release
    scripts:
      - git submodule update --init --recursive
  - name: mavros
    type: git
    repo: https://github.com/ctu-mrs/mavros
    sparse_paths:
      -
    rev: 8deab345e2560245c021b772cf675a9be54cee04
    link: ros_packages/mavros
    scripts:
      - git submodule update --init --recursive
  - name: mrs_bumper
    type: git
    repo: https://github.com/ctu-mrs/mrs_bumper.git
    sparse_paths:
      -
    rev: ba92968150f496be8dbbad9c71148ab50c83fb93
    link: ros_packages/mrs_bumper
    scripts:
      - git submodule update --init --recursive
  - name: mrs_lib
    type: git
    repo: https://github.com/ctu-mrs/mrs_lib.git
    sparse_paths:
      -
    rev: 2799a8c7e549388cb9a2742a125cfff0f9ebf5b8
    link: ros_packages/mrs_lib
    scripts:
      - git submodule update --init --recursive
  - name: mrs_mavros_interface
    type: git
    repo: https://github.com/ctu-mrs/mrs_mavros_interface.git
    sparse_paths:
      -
    rev: 651bc774ba088b30bc024f11e6456570809564d4
    link: ros_packages/mrs_mavros_interface
    scripts:
      - git submodule update --init --recursive
  - name: mrs_msgs
    type: git
    repo: https://github.com/ctu-mrs/mrs_msgs.git
    sparse_paths:
      -
    rev: 9dede53dae3ea18679ce1e3a445323667a924ace
    link: ros_packages/mrs_msgs
    scripts:
      - git submodule update --init --recursive
  - name: mrs_rviz_plugins
    type: git
    repo: https://github.com/ctu-mrs/mrs_rviz_plugins.git
    sparse_paths:
      -
    rev: 25e7e758e31084ccb31119742add6d283bc0b171
    link: ros_packages/mrs_rviz_plugins
    scripts:
      - git submodule update --init --recursive
  - name: mrs_uav_controllers
    type: git
    repo: https://github.com/ctu-mrs/mrs_uav_controllers.git
    sparse_paths:
      -
    rev: cd2b27da9533323842ff5125ca460ce56eae375d
    link: ros_packages/mrs_uav_controllers
    scripts:
      - git submodule update --init --recursive
  - name: mrs_uav_general
    type: git
    repo: https://github.com/ctu-mrs/mrs_uav_general.git
    sparse_paths:
      -
    rev: 42ef2595fb77960b640861ba9c2023dd40b0d4f1
    link: ros_packages/mrs_uav_general
    scripts:
      - git submodule update --init --recursive
  - name: mrs_uav_managers
    type: git
    repo: https://github.com/ctu-mrs/mrs_uav_managers.git
    sparse_paths:
      -
    rev: 5d49867cbd91a8685feaa80e212f688ad5a90b72
    link: ros_packages/mrs_uav_managers
    scripts:
      - git submodule update --init --recursive
  - name: mrs_uav_odometry
    type: git
    repo: https://github.com/ctu-mrs/mrs_uav_odometry.git
    sparse_paths:
      -
    rev: ac25fce679ec7483e2422d8bf2856ee4c10ddfd8
    link: ros_packages/mrs_uav_odometry
    scripts:
      - git submodule update --init --recursive
  - name: mrs_uav_status
    type: git
    repo: https://github.com/ctu-mrs/mrs_uav_status.git
    sparse_paths:
      -
    rev: 58c6708412923356406bc03a4ac459f475c722d7
    link: ros_packages/mrs_uav_status
    scripts:
      - git submodule update --init --recursive
  - name: mrs_uav_testing
    type: git
    repo: https://github.com/ctu-mrs/mrs_uav_testing.git
    sparse_paths:
      -
    rev: 71e20e2e1e3fa0bd594a1daf0dc920606794409d
    link: ros_packages/mrs_uav_testing
    scripts:
      - git submodule update --init --recursive
  - name: mrs_uav_trackers
    type: git
    repo: https://github.com/ctu-mrs/mrs_uav_trackers.git
    sparse_paths:
      -
    rev: 2d47db3bab8e2edaa7902d2003388c0ff5dd73f4
    link: ros_packages/mrs_uav_trackers
    scripts:
      - git submodule update --init --recursive
  - name: mrs_uav_trajectory_generation
    type: git
    repo: https://github.com/ctu-mrs/mrs_uav_trajectory_generation
    sparse_paths:
      -
    rev: a3920ea8fe67f4fae68e09212acb0fea1014e31b
    link: ros_packages/mrs_uav_trajectory_generation
    scripts:
      - git submodule update --init --recursive
  - name: nlopt_ros
    type: git
    repo: https://github.com/ctu-mrs/nlopt_ros
    sparse_paths:
      -
    rev: 5e351e81e8ee0c39d3096f38a0aa990304298631
    link: ros_packages/thirdparty/nlopt_ros
    scripts:
      - git submodule update --init --recursive
  - name: nodelet_core
    type: git
    repo: https://github.com/ctu-mrs/nodelet_core
    sparse_paths:
      -
    rev: b4344e75e9afa93010ffc20c3918ecfbab1848e4
    link: ros_packages/thirdparty/nodelet_core
    scripts:
      - git submodule update --init --recursive
  - name: tmux
    type: git
    repo: https://github.com/tmux/tmux.git
    sparse_paths:
      -
    rev: 25ae02869544b84b639b25b0aa69baa6ea2d3a6a
    link: utils/tmux
    scripts:
      - git submodule update --init --recursive
  - name: tmuxinator
    type: git
    repo: https://github.com/tmuxinator/tmuxinator.git
    sparse_paths:
      -
    rev: 7208ab2ed7c8cfbcbe92c4b0db2bc01550d40fd4
    link: utils/tmuxinator
    scripts:
      - git submodule update --init --recursive
default_group: ''
groups:
  -
